# -*- coding: utf-8 -*-
# Copyright 2019 Akretion
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).

{
    'name': 'SQL Export Mail',
    'version': '9.0.1.0.0',
    'author': 'Akretion,Odoo Community Association (OCA)',
    'website': 'http://github/oca/server-tools',
    'license': 'AGPL-3',
    'category': 'Generic Modules/Others',
    'summary': 'Send csv file generated by sql query by mail.',
    'depends': [
        'sql_export',
        'mail',
    ],
    'data': [
        'views/sql_export_view.xml',
        'mail_template.xml',
    ],
    'installable': True,
    }
