# Defaults for all prettier-supported languages.
# Prettier will complete this with settings from .editorconfig file.
bracketSpacing: false
printWidth: 88
proseWrap: always
semi: true
trailingComma: "es5"
xmlWhitespaceSensitivity: "strict"
useTabs: false
tabWidth: 2
overrides:
  - files: "*.xml"
    options:
      tabWidth: 4
