version: '3'
services:
  odoo:
    image: quay.io/numigi/odoo-base:11.12
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./log:/var/log/odoo
      - ./auto_backup:/mnt/extra-addons/auto_backup
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:8071:8071"
    depends_on:
      - db
    environment:
      - LOG_ODOO=/var/log/odoo
    command: odoo
  db:
    image: quay.io/numigi/postgres-odoo:11.1
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    expose:
      - 5432
volumes:
  odoo-web-data:
  odoo-db-data:
