from . import purge_wizard
from . import purge_modules
from . import purge_models
from . import purge_columns
from . import purge_tables
from . import purge_data
from . import purge_menus
from . import ir_model_fields
from . import create_indexes
