# -*- coding: utf-8 -*-
# Copyright (C) 2016-Today GRAP (http://www.grap.coop)
# @author: Sylvain LE GAL (https://twitter.com/legalsylvain)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).


- !record {model: mass.sort.config.line, id: mass_sort_config_line_1}:
    sequence: 1
    config_id: mass_sort_config
    field_id: field_mass_sort_config_line_field_id
    desc: False
