#!/usr/bin/env python3
# Copyright 2026 CORSA.pro (https://www.corsa.pro)
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
"""Rebuild static/src/css/fontawesome_editor.css from the bundled Font Awesome.

Odoo 19's HTML editor lists Font Awesome icons, and its email conversion turns
them into images, by reading ``.fa-name::before {content: "..."}`` rules from
the page's style sheets. Font Awesome 6 sets its icons through a CSS variable
(``.fa-name {--fa: "..."}``) instead, so with this module installed the editor
listed no icon and emails kept none. The generated file gives every icon such
a rule, drawn as ``fa fa-name`` markup draws it: the Font Awesome 4 names of
``v4-shims.css`` win over a Font Awesome 6 icon of the same name, as they do
on the page. Names drawing the same glyph in the same style share a rule,
shortest name first (the editor shows that one); brand and regular icons get
their font, so that ``fa fa-name`` draws them too.

Run it after updating the Font Awesome files::

    python3 base_fontawesome/scripts/build_editor_css.py
"""

import pathlib
import re
import sys
from collections import defaultdict

MODULE = pathlib.Path(__file__).resolve().parent.parent
COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
BLOCK = re.compile(r"\s*(@font-face\s*)?([^{}]*)\{([^{}]*)\}")
VARIABLE = re.compile(r'--fa:\s*"([^"]+)"')
FAMILY = re.compile(r"font-family:\s*['\"]([^'\"]+)['\"]")
WEIGHT = re.compile(r"font-weight:\s*(\d+)")
STYLES = {
    "solid": [],
    "regular": ['font-family: "Font Awesome 6 Free";', "font-weight: 400;"],
    "brands": ['font-family: "Font Awesome 6 Brands";', "font-weight: 400;"],
}


def blocks(css):
    """(is a font face, selectors, declarations) of each top-level block."""
    for font_face, selectors, body in BLOCK.findall(COMMENT.sub("", css)):
        yield bool(font_face), [part.strip() for part in selectors.split(",")], body


def font_awesome_6(css):
    """Name -> [codepoint, style]: the icons follow their font's @font-face."""
    icons = {}
    style = "solid"
    for font_face, selectors, body in blocks(css):
        if font_face:
            family = FAMILY.search(body)
            style = "brands" if family and "Brands" in family.group(1) else "solid"
            continue
        value = VARIABLE.search(body)
        for selector in selectors if value else ():
            name = re.fullmatch(r"\.fa-([a-z0-9-]+)", selector)
            if name:
                icons.setdefault(name.group(1), [value.group(1), style])
    return icons


def apply_v4_shims(icons, css):
    """The Font Awesome 4 names: their codepoint and style win on the page."""
    for _font_face, selectors, body in blocks(css):
        value = VARIABLE.search(body)
        family = FAMILY.search(body)
        weight = WEIGHT.search(body)
        for selector in selectors:
            name = re.fullmatch(r"\.fa\.fa-([a-z0-9-]+)", selector)
            if not name:
                continue
            icon = icons.setdefault(name.group(1), [None, "solid"])
            if value:
                icon[0] = value.group(1)
            if family and "Brands" in family.group(1):
                icon[1] = "brands"
            elif weight and weight.group(1) == "400":
                icon[1] = "regular"


def build(lib):
    css = lib / "css"
    icons = font_awesome_6((css / "all.css").read_text())
    apply_v4_shims(icons, (css / "v4-shims.css").read_text())
    names_by_glyph = defaultdict(list)
    for name, (codepoint, style) in icons.items():
        if codepoint:
            names_by_glyph[codepoint, style].append(name)
    rules = sorted(
        (sorted(names, key=lambda name: (len(name), name)), codepoint, style)
        for (codepoint, style), names in names_by_glyph.items()
    )
    lines = [
        "/* Generated by base_fontawesome/scripts/build_editor_css.py from",
        f"   {lib.name}: do not edit. Odoo's HTML editor and email conversion",
        "   read icons from ::before rules (see the script). */",
    ]
    # Formatted as prettier formats CSS, so that pre-commit leaves it as is.
    for names, codepoint, style in rules:
        lines.append(",\n".join(f".fa-{name}::before" for name in names) + " {")
        lines.append(f'    content: "{codepoint}";')
        lines.extend(f"    {declaration}" for declaration in STYLES[style])
        lines.append("}")
    return "\n".join(lines) + "\n", len(icons), len(rules)


def main():
    (lib,) = sorted((MODULE / "static/lib").glob("fontawesome-*"))
    content, names, glyphs = build(lib)
    target = MODULE / "static/src/css/fontawesome_editor.css"
    target.write_text(content)
    sys.stdout.write(f"{target.name}: {glyphs} icons, {names} names\n")


if __name__ == "__main__":
    main()
