# Copyright 2026 Heliconia Solutions Pvt. Ltd.
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo.addons.base.tests.common import BaseCommon


class TestBaseImportMailDisable(BaseCommon):
    def test_explicit_mail_handling(self):
        """Test the three edge cases explicitly covered by our mail.mail override."""
        self.partner.email = "silence@test.imports.invalid"
        template = self.env["mail.template"].create(
            {
                "name": "Dummy Template",
                "model_id": self.env["ir.model"]
                .search([("model", "=", "res.partner")], limit=1)
                .id,
                "body_html": "<p>Test</p>",
                "subject": "Dummy Subject",
            }
        )
        import_env = self.env(context=dict(self.env.context, import_file=True))

        # Case 1: message_post explicit call forcing a mail out
        import_env["res.partner"].browse(self.partner.id).message_post(
            body="Forced email",
            message_type="email",
            subtype_xmlid="mail.mt_comment",
            partner_ids=[self.partner.id],
        )

        # Case 2: mail.template explicit send
        import_env["mail.template"].browse(template.id).send_mail(
            self.partner.id, force_send=True
        )

        # Case 3: mail.mail raw creation
        mail = import_env["mail.mail"].create(
            {
                "subject": "Force Raw Mail Send",
                "body_html": "<p>Raw mail</p>",
                "email_to": self.partner.email,
            }
        )
        mail.send()
        spam_mails = self.env["mail.mail"].search(
            [("email_to", "=", self.partner.email)]
        )

        self.assertTrue(
            len(spam_mails) >= 1,
            "The mail records should have been technically generated by the "
            "explicit calls",
        )
        for spam_mail in spam_mails:
            self.assertEqual(
                spam_mail.state,
                "cancel",
                "The outgoing mail must be intercepted and permanently flagged "
                "as cancelled.",
            )
