{
    "name": "Google BigQuery",
    "summary": "Synchronize data in Odoo to BigQuery",
    "author": "Onestein, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/server-tools",
    "category": "Connector",
    "version": "15.0.1.0.0",
    "license": "AGPL-3",
    "development_status": "Alpha",
    "maintainers": ["tarteo"],
    "depends": ["base_setup", "mail", "queue_job"],
    "data": [
        "security/ir_model_access.xml",
        "security/ir_rule.xml",
        "data/ir_cron_data.xml",
        "data/google_bigquery_location_data.xml",
        "templates/onboarding.xml",
        "views/res_config_settings_view.xml",
        "views/ir_model_bigquery_view.xml",
        "views/ir_model_fields_bigquery_view.xml",
        "views/google_bigquery_location_view.xml",
        "views/menuitems.xml",
    ],
    "external_dependencies": {"python": ["google-cloud-bigquery"]},
    "icon": "/google_bigquery/static/description/icon.svg",
    "application": True,
}
