# Copyright 2026 manaTec GmbH (<https://manatec.de>)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl)

import re

from odoo import models


class IrSequence(models.Model):
    _inherit = "ir.sequence"

    def name_fits_sequence(self, name):
        """Helper function that determines whether a certain name
        could have been generated by the sequence"""
        self.ensure_one()
        pattern = self._get_sequence_regex_pattern()
        return bool(re.fullmatch(pattern, name))

    def _get_sequence_regex_pattern(self):
        """Returns a regular expression pattern matching the sequence definition"""
        self.ensure_one()

        # Regex patterns matching the valid formatting strings for
        # ir.sequence prefixes and suffixes
        format_strings = {
            "year": r"(19|20|21)\d{2}",
            "y": r"\d{2}",
            "month": r"(0[1-9]|1[0-2])",
            "day": r"(0[1-9]|[12][0-9]|3[01])",
            "doy": r"(0[0-9][1-9]|[12][0-9]{2}|3[0-5][0-9]|36[0-6])",
            "woy": r"([0-4][0-9]|5[0-3])",
            "weekday": r"([0-6])",
            "h12": r"(0[1-9]|1[0-2])",
            "h24": r"([01][0-9]|2[0-3])",
            "min": r"([0-5][0-9])",
            "sec": r"([0-5][0-9])",
        }
        # Regex pattern that matches all valid formatting strings
        # The formatting strings are inside a capturing group
        formatter_pattern = r"%\((" + "|".join(format_strings.keys()) + r")\)s"

        def parse_affixes(affix):
            # Uses re.split() to separate out the formatting strings
            # Since there are capturing groups inside the splitting regex,
            # the result alternates between split strings
            # and the captured group of the splitting string
            # Static parts (even indexes) are escaped into static regex patterns
            # Formatting strings (odd indexes) are replaced by their pattern
            return r"".join(
                re.escape(part) if i % 2 == 0 else format_strings.get(part, "")
                for i, part in enumerate(re.split(formatter_pattern, affix))
            )

        # Total pattern is:
        #   Prefix-matching pattern
        #   + number of digits at least equal to padding
        #   + Suffix-matching pattern
        return (
            parse_affixes(self.prefix or "")
            + r"\d{%d,}" % self.padding
            + parse_affixes(self.suffix or "")
        )
