[project]
name = "odoo-addons-oca-server-tools"
version = "19.0.20260520.0"
dependencies = [
    "odoo-addon-auditlog==19.0.*",
    "odoo-addon-base_cron_exclusion==19.0.*",
    "odoo-addon-base_exception==19.0.*",
    "odoo-addon-base_partition==19.0.*",
    "odoo-addon-base_technical_user==19.0.*",
    "odoo-addon-base_time_window==19.0.*",
    "odoo-addon-base_view_inheritance_extension==19.0.*",
    "odoo-addon-bus_alt_connection==19.0.*",
    "odoo-addon-database_cleanup==19.0.*",
    "odoo-addon-field_vector==19.0.*",
    "odoo-addon-iap_alternative_provider==19.0.*",
    "odoo-addon-module_auto_update==19.0.*",
    "odoo-addon-module_change_auto_install==19.0.*",
    "odoo-addon-onchange_helper==19.0.*",
    "odoo-addon-rpc_helper==19.0.*",
    "odoo-addon-scheduler_error_mailer==19.0.*",
    "odoo-addon-sequence_python==19.0.*",
    "odoo-addon-session_db==19.0.*",
    "odoo-addon-test_auditlog==19.0.*",
    "odoo-addon-tracking_manager==19.0.*",
    "odoo-addon-upgrade_analysis==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
