[project]
name = "odoo-addons-oca-server-tools"
version = "19.0.20251113.0"
dependencies = [
    "odoo-addon-base_exception==19.0.*",
    "odoo-addon-bus_alt_connection==19.0.*",
    "odoo-addon-session_db==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
