[project]
name = "odoo-addons-oca-server-tools"
version = "19.0.20260213.1"
dependencies = [
    "odoo-addon-auditlog==19.0.*",
    "odoo-addon-base_exception==19.0.*",
    "odoo-addon-base_partition==19.0.*",
    "odoo-addon-base_technical_user==19.0.*",
    "odoo-addon-base_view_inheritance_extension==19.0.*",
    "odoo-addon-bus_alt_connection==19.0.*",
    "odoo-addon-database_cleanup==19.0.*",
    "odoo-addon-field_vector==19.0.*",
    "odoo-addon-module_change_auto_install==19.0.*",
    "odoo-addon-sequence_python==19.0.*",
    "odoo-addon-session_db==19.0.*",
    "odoo-addon-test_auditlog==19.0.*",
    "odoo-addon-upgrade_analysis==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
